### ISSUE TITLE
PackageName for AndroidTest causes check to fail

### ISSUE THREAD

**Issue by tasomaniac** [RBusarow/ModuleCheck#402]
We have custom packageName for AndroidManifest.xml for AndroidTest. Don't ask me why. :) I don't know but I'm too afraid to remove. This causes ModuleCheck to exit early

I guess it is nice to also check test dependencies but they're not as important as others. Any suggestions?

### To reproduce

Add AndroidManifest.xml under `/app/src/androidTest/AndroidManifest.xml`

```
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.test"/>
```

### Error

```
> Task :moduleCheck FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':moduleCheck'.
> ModuleCheck only supports a single base package.  The following packages are present for module `:app`:
  
  com.example.test
  com.example
````

**Comment by tasomaniac** [comment]
I guess this is the same as #372

**Comment by RBusarow** [comment]
> Don't ask me why. :) I don't know but I'm too afraid to remove
🤣 

Thanks for the report, again.  This actually became a blocker for me just last week, and I had the fix stashed.  This is now fixed in the current snapshot.

**Comment by tasomaniac** [comment]
Thanks. It is also a blocker for our project. Amazing you have it fixed so fast
