### ISSUE TITLE
Build speed optimization when BuildConfig is disabled

### ISSUE THREAD

**Issue by tasomaniac** [RBusarow/ModuleCheck#453]
At the moment ModuleCheck always depends on BuildConfig task. Before it runs, it would first force all modules to generate BuildConfig. While running on my project, I realized that this took long. That was not expected since we have BuildConfig disabled via the following property

```
android.defaults.buildfeatures.buildconfig = false
```

Even if it is disabled, ModuleCheck would force them to be generated. This is not needed

**Comment by tasomaniac** [comment]
In my [auto-manifest plugin](https://github.com/GradleUp/auto-manifest/), I did the optimization simply by using `mustRunAfter` instead of `dependsOn`. It works well there because manifest generation is needed while running the regular build and BuildConfig generation task will run only when needed. 

Here we cannot run `mustRunAfter` because if we do, it will never be triggered.

Seems like the only option is to make this `dependsOn` relationship based on the enablement state of `buildconfig`

**Comment by RBusarow** [comment]
Thanks!  This makes sense.
